import { IconDefinition } from '@fortawesome/fontawesome-svg-core';
import {
  faObjectUngroup,
  faScissors,
  faCompress,
  faFileWord,
  faFilePdf,
  faFileExcel,
  faFilePowerpoint,
  faPenToSquare,
  faFileImage,
  faSignature,
  faStamp,
  faRotate,
  faCode,
  faLockOpen,
  faShield,
  faLayerGroup,
  faWrench,
  faHashtag,
  faFileLines,
  faEye,
  faFileCircleCheck,
  faCrop,
  faCopy,
  faFileShield,
} from '@fortawesome/free-solid-svg-icons';

export interface ToolConfig {
  id: string;
  title: string;
  description: string;
  icon: IconDefinition;
  iconBgColor: string;
  iconColor: string;
  pageTitle: string;
  pageDescription: string;
  isNew?: boolean;
}

export const toolsConfig: Record<string, ToolConfig> = {
  'merge': {
    id: 'merge',
    title: 'Merge PDF',
    description: 'Combine PDFs in the order you want with the easiest PDF merger available.',
    icon: faObjectUngroup,
    iconBgColor: 'bg-orange-100',
    iconColor: 'text-orange-600',
    pageTitle: 'Merge PDF Files',
    pageDescription: 'Combine multiple PDF documents into a single file. Simply upload your files, arrange them in the desired order, and merge them together.',
  },
  'split': {
    id: 'split',
    title: 'Split PDF',
    description: 'Separate one page or a whole set for easy conversion into independent PDF files.',
    icon: faScissors,
    iconBgColor: 'bg-orange-100',
    iconColor: 'text-orange-600',
    pageTitle: 'Split PDF Files',
    pageDescription: 'Extract pages from a PDF or save each page as a separate file. Choose specific pages or split by page ranges.',
  },
  'compress': {
    id: 'compress',
    title: 'Compress PDF',
    description: 'Reduce file size while optimizing for maximal PDF quality.',
    icon: faCompress,
    iconBgColor: 'bg-green-100',
    iconColor: 'text-green-600',
    pageTitle: 'Compress PDF Files',
    pageDescription: 'Reduce the file size of your PDF while maintaining quality. Perfect for sharing and storage optimization.',
  },
  'pdf-to-word': {
    id: 'pdf-to-word',
    title: 'PDF to Word',
    description: 'Easily convert your PDF files into easy to edit DOC and DOCX documents. The converted WORD document is almost 100% accurate.',
    icon: faFileWord,
    iconBgColor: 'bg-blue-100',
    iconColor: 'text-blue-600',
    pageTitle: 'Convert PDF to Word',
    pageDescription: 'Easily convert your PDF files into easy to edit DOC and DOCX documents. The converted WORD document is almost 100% accurate.',
  },
  'pdf-to-ppt': {
    id: 'pdf-to-ppt',
    title: 'PDF to PowerPoint',
    description: 'Turn your PDF files into easy to edit PPT and PPTX slideshows.',
    icon: faFilePowerpoint,
    iconBgColor: 'bg-orange-100',
    iconColor: 'text-orange-600',
    pageTitle: 'Convert PDF to PowerPoint',
    pageDescription: 'Turn your PDF files into easy to edit PPT and PPTX slideshows.',
  },
  'pdf-to-excel': {
    id: 'pdf-to-excel',
    title: 'PDF to Excel',
    description: 'Pull data straight from PDFs into Excel spreadsheets in a few short seconds.',
    icon: faFileExcel,
    iconBgColor: 'bg-green-100',
    iconColor: 'text-green-600',
    pageTitle: 'Convert PDF to Excel',
    pageDescription: 'Pull data straight from PDFs into Excel spreadsheets in a few short seconds.',
  },
  'word-to-pdf': {
    id: 'word-to-pdf',
    title: 'Word to PDF',
    description: 'Make DOC and DOCX files easy to read by converting them to PDF.',
    icon: faFilePdf,
    iconBgColor: 'bg-blue-100',
    iconColor: 'text-blue-600',
    pageTitle: 'Convert Word to PDF',
    pageDescription: 'Make DOC and DOCX files easy to read by converting them to PDF.',
  },
  'ppt-to-pdf': {
    id: 'ppt-to-pdf',
    title: 'PowerPoint to PDF',
    description: 'Make PPT and PPTX slideshows easy to view by converting them to PDF.',
    icon: faFilePdf,
    iconBgColor: 'bg-orange-100',
    iconColor: 'text-orange-600',
    pageTitle: 'Convert PowerPoint to PDF',
    pageDescription: 'Make PPT and PPTX slideshows easy to view by converting them to PDF.',
  },
  'excel-to-pdf': {
    id: 'excel-to-pdf',
    title: 'Excel to PDF',
    description: 'Make EXCEL spreadsheets easy to read by converting them to PDF.',
    icon: faFilePdf,
    iconBgColor: 'bg-green-100',
    iconColor: 'text-green-600',
    pageTitle: 'Convert Excel to PDF',
    pageDescription: 'Make EXCEL spreadsheets easy to read by converting them to PDF.',
  },
  'edit-pdf': {
    id: 'edit-pdf',
    title: 'Edit PDF',
    description: 'Add text, images, shapes or freehand annotations to a PDF document. Edit the size, font, and color of the added content.',
    icon: faPenToSquare,
    iconBgColor: 'bg-purple-100',
    iconColor: 'text-purple-600',
    pageTitle: 'Edit PDF Files',
    pageDescription: 'Add text, images, shapes or freehand annotations to a PDF document. Edit the size, font, and color of the added content.',
    isNew: true,
  },
  'replace-text-pdf': {
    id: 'replace-text-pdf',
    title: 'Replace Text in PDF',
    description: 'Find and replace text in PDF documents. Replace specific text occurrences while maintaining formatting.',
    icon: faFileLines,
    iconBgColor: 'bg-green-100',
    iconColor: 'text-green-600',
    pageTitle: 'Replace Text in PDF',
    pageDescription: 'Find and replace text in PDF documents. Replace specific text occurrences while maintaining formatting.',
    isNew: true,
  },
  'pdf-to-jpg': {
    id: 'pdf-to-jpg',
    title: 'PDF to JPG',
    description: 'Convert each PDF page into a JPG or extract all images contained in a PDF.',
    icon: faFileImage,
    iconBgColor: 'bg-yellow-100',
    iconColor: 'text-yellow-600',
    pageTitle: 'Convert PDF to JPG',
    pageDescription: 'Convert each PDF page into a JPG or extract all images contained in a PDF.',
  },
  'jpg-to-pdf': {
    id: 'jpg-to-pdf',
    title: 'JPG to PDF',
    description: 'Convert JPG images to PDF in seconds. Easily adjust orientation and margins.',
    icon: faFileImage,
    iconBgColor: 'bg-yellow-100',
    iconColor: 'text-yellow-600',
    pageTitle: 'Convert JPG to PDF',
    pageDescription: 'Convert JPG images to PDF in seconds. Easily adjust orientation and margins.',
  },
  'sign-pdf': {
    id: 'sign-pdf',
    title: 'Sign PDF',
    description: 'Sign yourself or request electronic signatures from others.',
    icon: faSignature,
    iconBgColor: 'bg-blue-100',
    iconColor: 'text-blue-600',
    pageTitle: 'Sign PDF Files',
    pageDescription: 'Sign yourself or request electronic signatures from others.',
  },
  'watermark': {
    id: 'watermark',
    title: 'Watermark',
    description: 'Stamp an image or text over your PDF in seconds. Choose the typography, transparency and position.',
    icon: faStamp,
    iconBgColor: 'bg-purple-100',
    iconColor: 'text-purple-600',
    pageTitle: 'Add Watermark to PDF',
    pageDescription: 'Stamp an image or text over your PDF in seconds. Choose the typography, transparency and position.',
  },
  'rotate-pdf': {
    id: 'rotate-pdf',
    title: 'Rotate PDF',
    description: 'Rotate your PDFs the way you need them. You can even rotate multiple PDFs at once!',
    icon: faRotate,
    iconBgColor: 'bg-green-100',
    iconColor: 'text-green-600',
    pageTitle: 'Rotate PDF Files',
    pageDescription: 'Rotate your PDFs the way you need them. You can even rotate multiple PDFs at once!',
  },
  'html-to-pdf': {
    id: 'html-to-pdf',
    title: 'HTML to PDF',
    description: 'Convert webpages in HTML to PDF. Copy and paste the URL of the page you want and convert it to PDF with a click.',
    icon: faCode,
    iconBgColor: 'bg-yellow-100',
    iconColor: 'text-yellow-600',
    pageTitle: 'Convert HTML to PDF',
    pageDescription: 'Convert webpages in HTML to PDF. Copy and paste the URL of the page you want and convert it to PDF with a click.',
  },
  'pdf-to-html': {
    id: 'pdf-to-html',
    title: 'PDF to HTML',
    description: 'Convert PDF files to well-formatted HTML documents with proper structure, headings, and formatting preserved.',
    icon: faCode,
    iconBgColor: 'bg-purple-100',
    iconColor: 'text-purple-600',
    pageTitle: 'Convert PDF to HTML',
    pageDescription: 'Convert PDF files to well-formatted HTML documents with proper structure, headings, paragraphs, lists, and formatting preserved.',
  },
  'unlock-pdf': {
    id: 'unlock-pdf',
    title: 'Unlock PDF',
    description: 'Remove PDF password security, giving you the freedom to use your PDFs as you want.',
    icon: faLockOpen,
    iconBgColor: 'bg-blue-100',
    iconColor: 'text-blue-600',
    pageTitle: 'Unlock PDF Files',
    pageDescription: 'Remove PDF password security, giving you the freedom to use your PDFs as you want.',
  },
  'protect-pdf': {
    id: 'protect-pdf',
    title: 'Protect PDF',
    description: 'Protect PDF files with a password. Encrypt PDF documents to prevent unauthorized access.',
    icon: faShield,
    iconBgColor: 'bg-blue-100',
    iconColor: 'text-blue-600',
    pageTitle: 'Protect PDF Files',
    pageDescription: 'Protect PDF files with a password. Encrypt PDF documents to prevent unauthorized access.',
  },
  'organize-pdf': {
    id: 'organize-pdf',
    title: 'Organize PDF',
    description: 'Sort pages of your PDF file however you like. Delete PDF pages or add PDF pages to your document at your convenience.',
    icon: faLayerGroup,
    iconBgColor: 'bg-orange-100',
    iconColor: 'text-orange-600',
    pageTitle: 'Organize PDF Files',
    pageDescription: 'Sort pages of your PDF file however you like. Delete PDF pages or add PDF pages to your document at your convenience.',
  },
  'pdf-to-pdfa': {
    id: 'pdf-to-pdfa',
    title: 'PDF to PDF/A',
    description: 'Transform your PDF to PDF/A, the ISO-standardized version of PDF for long-term archiving. Your PDF will preserve formatting when accessed in the future.',
    icon: faFileCircleCheck,
    iconBgColor: 'bg-blue-100',
    iconColor: 'text-blue-600',
    pageTitle: 'Convert PDF to PDF/A',
    pageDescription: 'Transform your PDF to PDF/A, the ISO-standardized version of PDF for long-term archiving. Your PDF will preserve formatting when accessed in the future.',
  },
  'repair-pdf': {
    id: 'repair-pdf',
    title: 'Repair PDF',
    description: 'Repair a damaged PDF and recover data from corrupt PDF. Fix PDF files with our Repair tool.',
    icon: faWrench,
    iconBgColor: 'bg-green-100',
    iconColor: 'text-green-600',
    pageTitle: 'Repair PDF Files',
    pageDescription: 'Repair a damaged PDF and recover data from corrupt PDF. Fix PDF files with our Repair tool.',
  },
  'page-numbers': {
    id: 'page-numbers',
    title: 'Page numbers',
    description: 'Add page numbers into PDFs with ease. Choose your positions, dimensions, typography.',
    icon: faHashtag,
    iconBgColor: 'bg-purple-100',
    iconColor: 'text-purple-600',
    pageTitle: 'Add Page Numbers to PDF',
    pageDescription: 'Add page numbers into PDFs with ease. Choose your positions, dimensions, typography.',
  },
  'scan-to-pdf': {
    id: 'scan-to-pdf',
    title: 'Scan to PDF',
    description: 'Capture document scans from your mobile device and send them instantly to your browser.',
    icon: faFileLines,
    iconBgColor: 'bg-orange-100',
    iconColor: 'text-orange-600',
    pageTitle: 'Scan to PDF',
    pageDescription: 'Capture document scans from your mobile device and send them instantly to your browser.',
  },
  'ocr-pdf': {
    id: 'ocr-pdf',
    title: 'OCR PDF',
    description: 'Easily convert scanned PDF into searchable and selectable documents.',
    icon: faEye,
    iconBgColor: 'bg-green-100',
    iconColor: 'text-green-600',
    pageTitle: 'OCR PDF Files',
    pageDescription: 'Easily convert scanned PDF into searchable and selectable documents.',
  },
  'compare-pdf': {
    id: 'compare-pdf',
    title: 'Compare PDF',
    description: 'Show a side-by-side document comparison and easily spot changes between different file versions.',
    icon: faCopy,
    iconBgColor: 'bg-blue-100',
    iconColor: 'text-blue-600',
    pageTitle: 'Compare PDF Files',
    pageDescription: 'Show a side-by-side document comparison and easily spot changes between different file versions.',
    isNew: true,
  },
  'redact-pdf': {
    id: 'redact-pdf',
    title: 'Redact PDF',
    description: 'Redact text and graphics to permanently remove sensitive information from a PDF.',
    icon: faFileShield,
    iconBgColor: 'bg-red-100',
    iconColor: 'text-red-600',
    pageTitle: 'Redact PDF Files',
    pageDescription: 'Redact text and graphics to permanently remove sensitive information from a PDF.',
    isNew: true,
  },
  'crop-pdf': {
    id: 'crop-pdf',
    title: 'Crop PDF',
    description: 'Crop margins of PDF documents or select specific areas, then apply the changes to one page or the whole document.',
    icon: faCrop,
    iconBgColor: 'bg-purple-100',
    iconColor: 'text-purple-600',
    pageTitle: 'Crop PDF Files',
    pageDescription: 'Crop margins of PDF documents or select specific areas, then apply the changes to one page or the whole document.',
    isNew: true,
  },
};

